# Generated by Django 5.2.8 on 2025-12-01 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advisory',
            fields=[
                ('advisory_id', models.AutoField(primary_key=True, serialize=False)),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('sector', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('message', models.TextField()),
                ('recipients_count', models.IntegerField(default=0)),
                ('send_now', models.BooleanField(default=False)),
                ('status', models.CharField(default='DRAFT', max_length=20)),
                ('sent_date_time', models.DateTimeField(blank=True, null=True)),
                ('date_time_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'advisories',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_id', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=10)),
                ('country_is_deleted', models.BooleanField(default=False)),
                ('record_version', models.IntegerField(default=1)),
                ('date_time_added', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.IntegerField(blank=True, null=True)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('date_time_modified', models.DateTimeField(auto_now=True)),
                ('modified_by', models.IntegerField(blank=True, null=True)),
                ('latest_ip', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'db_table': 'countries',
            },
        ),
        migrations.CreateModel(
            name='CoverType',
            fields=[
                ('cover_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('cover_type', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('deleted', models.BooleanField(default=False)),
                ('date_time_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cover_types',
            },
        ),
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('crop_id', models.AutoField(db_column='cropId', primary_key=True, serialize=False)),
                ('crop', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.BooleanField(default=True)),
                ('deleted', models.BooleanField(default=False)),
                ('record_version', models.IntegerField(db_column='recordVersion', default=1)),
                ('date_time_added', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'crops',
            },
        ),
        migrations.CreateModel(
            name='OrganizationType',
            fields=[
                ('organisation_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('organisation_type', models.CharField(max_length=100)),
                ('organisation_type_description', models.TextField(blank=True, null=True)),
                ('organisation_type_status', models.CharField(default='ACTIVE', max_length=20)),
                ('record_version', models.IntegerField(default=1)),
                ('date_time_added', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.IntegerField(blank=True, null=True)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('date_time_modified', models.DateTimeField(auto_now=True)),
                ('modified_by', models.IntegerField(blank=True, null=True)),
                ('latest_ip', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'db_table': 'organisation_types',
            },
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('weather_id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=200)),
                ('data_type', models.CharField(max_length=50)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recorded_at', models.DateTimeField()),
                ('date_time_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'weather_data',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_type', models.CharField(default='API USER', max_length=50)),
                ('user_name', models.CharField(max_length=200)),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('user_msisdn', models.CharField(blank=True, max_length=20, null=True)),
                ('user_status', models.CharField(default='ACTIVE', max_length=20)),
                ('failed_logins', models.IntegerField(default=0)),
                ('locked_till_date_time', models.DateTimeField(blank=True, null=True)),
                ('reset_code', models.CharField(blank=True, max_length=100, null=True)),
                ('reset_password', models.BooleanField(default=False)),
                ('date_time_added', models.DateTimeField(auto_now_add=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='insurance.country')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('farmer_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('id_number', models.CharField(max_length=50, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('farmer_category', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
                ('date_time_added', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='insurance.country')),
            ],
            options={
                'db_table': 'farmers',
            },
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('farm_id', models.AutoField(primary_key=True, serialize=False)),
                ('farm_name', models.CharField(max_length=200)),
                ('farm_size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_of_measure', models.CharField(max_length=20)),
                ('location_province', models.CharField(blank=True, max_length=100, null=True)),
                ('location_district', models.CharField(blank=True, max_length=100, null=True)),
                ('location_sector', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
                ('date_time_added', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='farms', to='insurance.farmer')),
            ],
            options={
                'db_table': 'farms',
            },
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('claim_id', models.AutoField(primary_key=True, serialize=False)),
                ('claim_number', models.CharField(max_length=100, unique=True)),
                ('estimated_loss_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('status', models.CharField(default='OPEN', max_length=30)),
                ('claim_date', models.DateTimeField(auto_now_add=True)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='insurance.farmer')),
            ],
            options={
                'db_table': 'claims',
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('bank_account_id', models.AutoField(primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=50)),
                ('account_name', models.CharField(max_length=200)),
                ('date_time_added', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='insurance.farmer')),
            ],
            options={
                'db_table': 'bank_accounts',
            },
        ),
        migrations.CreateModel(
            name='LossAssessor',
            fields=[
                ('assessor_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
                ('date_time_added', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'loss_assessors',
            },
        ),
        migrations.CreateModel(
            name='ClaimAssignment',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('assigned_by', models.IntegerField()),
                ('assignment_date', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance.claim')),
                ('loss_assessor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='insurance.lossassessor')),
            ],
            options={
                'db_table': 'claim_assignments',
            },
        ),
        migrations.AddField(
            model_name='claim',
            name='loss_assessor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='insurance.lossassessor'),
        ),
        migrations.CreateModel(
            name='NextOfKin',
            fields=[
                ('next_of_kin_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('relationship', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('date_time_added', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_of_kin', to='insurance.farmer')),
            ],
            options={
                'db_table': 'next_of_kin',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('organisation_id', models.AutoField(primary_key=True, serialize=False)),
                ('organisation_code', models.CharField(max_length=50, unique=True)),
                ('organisation_name', models.CharField(max_length=200)),
                ('organisation_email', models.EmailField(max_length=254)),
                ('organisation_msisdn', models.CharField(max_length=20)),
                ('organisation_contact', models.CharField(max_length=200)),
                ('organisation_physical_address', models.TextField(blank=True, null=True)),
                ('organisation_status', models.CharField(default='ACTIVE', max_length=20)),
                ('organisation_is_deleted', models.BooleanField(default=False)),
                ('failed_login_threshold', models.IntegerField(default=5)),
                ('failed_login_backoff', models.IntegerField(default=30)),
                ('record_version', models.IntegerField(default=1)),
                ('date_time_added', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.IntegerField(blank=True, null=True)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('date_time_modified', models.DateTimeField(auto_now=True)),
                ('modified_by', models.IntegerField(blank=True, null=True)),
                ('latest_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('country', models.ForeignKey(db_column='country_id', on_delete=django.db.models.deletion.PROTECT, to='insurance.country')),
                ('organisation_type', models.ForeignKey(db_column='organisation_type_id', on_delete=django.db.models.deletion.PROTECT, to='insurance.organizationtype')),
            ],
            options={
                'db_table': 'organisations',
            },
        ),
        migrations.AddField(
            model_name='lossassessor',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='insurance.organization'),
        ),
        migrations.AddField(
            model_name='farmer',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='insurance.organization'),
        ),
        migrations.CreateModel(
            name='CropVariety',
            fields=[
                ('crop_variety_id', models.AutoField(primary_key=True, serialize=False)),
                ('crop_variety', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('deleted', models.BooleanField(default=False)),
                ('record_version', models.IntegerField(default=1)),
                ('date_time_added', models.DateTimeField(auto_now_add=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='insurance.crop')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='insurance.organization')),
            ],
            options={
                'db_table': 'crop_varieties',
            },
        ),
        migrations.AddField(
            model_name='crop',
            name='organisation',
            field=models.ForeignKey(db_column='organisationId', on_delete=django.db.models.deletion.PROTECT, to='insurance.organization'),
        ),
        migrations.AddField(
            model_name='user',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='insurance.organization'),
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('product_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_category', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('deleted', models.BooleanField(default=False)),
                ('date_time_added', models.DateTimeField(auto_now_add=True)),
                ('cover_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='insurance.covertype')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='insurance.organization')),
            ],
            options={
                'db_table': 'product_categories',
            },
        ),
        migrations.CreateModel(
            name='InsuranceProduct',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200)),
                ('average_premium_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sum_insured', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
                ('date_time_added', models.DateTimeField(auto_now_add=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='insurance.crop')),
                ('crop_variety', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='insurance.cropvariety')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='insurance.organization')),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='insurance.productcategory')),
            ],
            options={
                'db_table': 'insurance_products',
            },
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('quotation_id', models.AutoField(primary_key=True, serialize=False)),
                ('policy_number', models.CharField(blank=True, max_length=100, null=True)),
                ('premium_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('sum_insured', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(default='OPEN', max_length=20)),
                ('quotation_date', models.DateTimeField(auto_now_add=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='insurance.farm')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='insurance.farmer')),
                ('insurance_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='insurance.insuranceproduct')),
            ],
            options={
                'db_table': 'quotations',
            },
        ),
        migrations.AddField(
            model_name='claim',
            name='quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='insurance.quotation'),
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('season_id', models.AutoField(primary_key=True, serialize=False)),
                ('season', models.CharField(max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('deleted', models.BooleanField(default=False)),
                ('date_time_added', models.DateTimeField(auto_now_add=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='insurance.organization')),
            ],
            options={
                'db_table': 'seasons',
            },
        ),
        migrations.AddField(
            model_name='insuranceproduct',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='insurance.season'),
        ),
        migrations.CreateModel(
            name='Subsidy',
            fields=[
                ('subsidy_id', models.AutoField(primary_key=True, serialize=False)),
                ('subsidy_name', models.CharField(max_length=200)),
                ('subsidy_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
                ('date_time_added', models.DateTimeField(auto_now_add=True)),
                ('insurance_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='insurance.insuranceproduct')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='insurance.organization')),
            ],
            options={
                'db_table': 'subsidies',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('settlement_date', models.DateTimeField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('date_time_added', models.DateTimeField(auto_now_add=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='insurance.organization')),
                ('subsidy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='insurance.subsidy')),
            ],
            options={
                'db_table': 'invoices',
            },
        ),
    ]
