# Generated by Django 5.2.8 on 2025-11-28 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_id', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=10)),
                ('country_is_deleted', models.BooleanField(default=False)),
                ('record_version', models.IntegerField(default=1)),
                ('date_time_added', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.IntegerField(blank=True, null=True)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('date_time_modified', models.DateTimeField(auto_now=True)),
                ('modified_by', models.IntegerField(blank=True, null=True)),
                ('latest_ip', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'db_table': 'countries',
            },
        ),
        migrations.CreateModel(
            name='OrganizationType',
            fields=[
                ('organisation_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('organisation_type', models.CharField(max_length=100)),
                ('organisation_type_description', models.TextField(blank=True, null=True)),
                ('organisation_type_status', models.CharField(default='ACTIVE', max_length=20)),
                ('record_version', models.IntegerField(default=1)),
                ('date_time_added', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.IntegerField(blank=True, null=True)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('date_time_modified', models.DateTimeField(auto_now=True)),
                ('modified_by', models.IntegerField(blank=True, null=True)),
                ('latest_ip', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'db_table': 'organisation_types',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('organisation_id', models.AutoField(primary_key=True, serialize=False)),
                ('organisation_code', models.CharField(max_length=50, unique=True)),
                ('organisation_name', models.CharField(max_length=200)),
                ('organisation_email', models.EmailField(max_length=254)),
                ('organisation_msisdn', models.CharField(max_length=20)),
                ('organisation_contact', models.CharField(max_length=200)),
                ('organisation_physical_address', models.TextField(blank=True, null=True)),
                ('organisation_status', models.CharField(default='ACTIVE', max_length=20)),
                ('organisation_is_deleted', models.BooleanField(default=False)),
                ('failed_login_threshold', models.IntegerField(default=5)),
                ('failed_login_backoff', models.IntegerField(default=30)),
                ('record_version', models.IntegerField(default=1)),
                ('date_time_added', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.IntegerField(blank=True, null=True)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('date_time_modified', models.DateTimeField(auto_now=True)),
                ('modified_by', models.IntegerField(blank=True, null=True)),
                ('latest_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('country', models.ForeignKey(db_column='country_id', on_delete=django.db.models.deletion.PROTECT, to='insurance.country')),
                ('organisation_type', models.ForeignKey(db_column='organisation_type_id', on_delete=django.db.models.deletion.PROTECT, to='insurance.organizationtype')),
            ],
            options={
                'db_table': 'organisations',
            },
        ),
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('crop_id', models.AutoField(db_column='cropId', primary_key=True, serialize=False)),
                ('crop', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.BooleanField(default=True)),
                ('deleted', models.BooleanField(default=False)),
                ('record_version', models.IntegerField(db_column='recordVersion', default=1)),
                ('date_time_added', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.IntegerField(blank=True, null=True)),
                ('organisation', models.ForeignKey(db_column='organisationId', on_delete=django.db.models.deletion.PROTECT, to='insurance.organization')),
            ],
            options={
                'db_table': 'crops',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_type', models.CharField(default='API USER', max_length=50)),
                ('user_name', models.CharField(max_length=200)),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('user_msisdn', models.CharField(blank=True, max_length=20, null=True)),
                ('user_status', models.CharField(default='ACTIVE', max_length=20)),
                ('failed_logins', models.IntegerField(default=0)),
                ('locked_till_date_time', models.DateTimeField(blank=True, null=True)),
                ('reset_code', models.CharField(blank=True, max_length=100, null=True)),
                ('reset_password', models.BooleanField(default=False)),
                ('date_time_added', models.DateTimeField(auto_now_add=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='insurance.country')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='insurance.organization')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
