# Generated by Django 5.2.8 on 2025-12-01 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_active',
            new_name='user_is_active',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_msisdn',
            new_name='user_phone_number',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_type',
            new_name='user_role',
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
