# Generated by Django 5.2.8 on 2025-12-11 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0002_rename_is_active_user_user_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='loss_details',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
