# Generated by Django 5.2.8 on 2025-12-17 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0003_claim_loss_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleType',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=100, unique=True)),
                ('role_description', models.TextField(blank=True, null=True)),
                ('role_status', models.CharField(default='ACTIVE', max_length=20)),
                ('permissions', models.JSONField(blank=True, null=True)),
                ('is_system_role', models.BooleanField(default=False)),
                ('date_time_added', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.IntegerField(blank=True, null=True)),
                ('date_time_modified', models.DateTimeField(auto_now=True)),
                ('modified_by', models.IntegerField(blank=True, null=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='insurance.organization')),
            ],
        ),
    ]
