# Generated by Django 5.2.8 on 2025-12-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0005_message_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roletype',
            options={'verbose_name_plural': 'Role Types'},
        ),
        migrations.AlterModelOptions(
            name='weatherdata',
            options={'ordering': ['-recorded_at']},
        ),
        migrations.AddField(
            model_name='advisory',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='status',
            field=models.CharField(default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='data_type',
            field=models.CharField(choices=[('HISTORICAL', 'Historical'), ('FORECAST', 'Forecast')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='weatherdata',
            index=models.Index(fields=['location', 'data_type'], name='weather_dat_locatio_5d4875_idx'),
        ),
        migrations.AddIndex(
            model_name='weatherdata',
            index=models.Index(fields=['recorded_at'], name='weather_dat_recorde_97c0e8_idx'),
        ),
        migrations.AlterModelTable(
            name='roletype',
            table='role_types',
        ),
    ]
