# Generated by Django 5.2.8 on 2025-12-24 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0006_alter_roletype_options_alter_weatherdata_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimPhoto',
            fields=[
                ('photo_id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(upload_to='claim_photos/%Y/%m/%d/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='insurance.claim')),
            ],
            options={
                'db_table': 'claim_photos',
            },
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('inspection_id', models.AutoField(primary_key=True, serialize=False)),
                ('inspection_type', models.CharField(choices=[('PRE_PLANTING', 'Pre-Planting'), ('MID_SEASON', 'Mid-Season'), ('PRE_HARVEST', 'Pre-Harvest'), ('LOSS_ASSESSMENT', 'Loss Assessment')], max_length=20)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.TimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('check_in_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('check_in_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('check_out_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('check_out_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('findings', models.JSONField(blank=True, default=dict)),
                ('recommendations', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='insurance.farm')),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_inspections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inspections',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='InspectionPhoto',
            fields=[
                ('photo_id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(upload_to='inspection_photos/%Y/%m/%d/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('taken_at', models.DateTimeField(auto_now_add=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='insurance.inspection')),
            ],
            options={
                'db_table': 'inspection_photos',
            },
        ),
    ]
